name: Upload to S3

on:
  push:
    branches:
      - main
      - develop

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Verify AWS CLI
        run: aws --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SALVA }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SALVA }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_SALVA }}
          aws-region: eu-west-3

      - name: Set S3 Bucket Location
        run: echo "S3_BUCKET=s3://proyect-1-stb-devops-bucket" >> $GITHUB_ENV

      - name: Check for changes in docs folder
        id: changes
        run: |
          git diff --exit-code ./docs || echo "Changes detected in docs folder"

      - name: Upload Changes to S3
        if: steps.changes.outputs.stdout != ''
        run: |
          aws s3 sync ./docs ${{ env.S3_BUCKET }}/docs --exact-timestamps
