name: Upload to S3

on:
  push:
    branches:
      - main
      - develop

jobs:
  install-aws-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Verify AWS CLI
        run: aws --version
